### ISSUE TITLE
Writing the initial proposal

### ISSUE THREAD

**Issue by santina** [santina/CrystalMethylation#1]
# Introduction: 
* What's CRC (colorectal cancer) 
* DNA methylation
* how they're related (cancer and methylation, and CRC in specific)

# Part 1: Why's 
* Why we pick this dataset 
    - 2014 - recent 
* other justification 

# Part 2: About the data 
* Description of the dataset 
    - the three groups (normal ,adenoma, CRC) 
    - the types of data (probes, samples,  how it's generated generated from the array) 
    - details about data files 

# Part 3: the Questions we want to answer 
* Can we identify differential DNA methylation patterns that underlie the progression of CRC? 

# Part 4: Our Approach 
* there are ~ 500K probes, so we will need to limit that
    - looking at important genes + some randomly selected locations 
* other things we might need to do
   - reformatting and cleaning data
   - build a pipeline

**Comment by evayap** [comment]
The intro is just a draft. I'll make some changes tomorrow.

**Comment by santina** [comment]
part 4 was updated to this (copied pasted from group_proposal.md before I deleted that section) 
# Part 3: Proposed work  
* Proposed workflow/pipeline
  * 1. Downsize dataset
      - Select probes targeting gene of interest and randomly select the rest of the probes
      - select probes near CPG islands
  * 2. Data reshaping and exploratory analysis of raw data
      - Perform data cleaning and reformatting as needed
      - Exploratory analysis of raw data such as mapping missing values(NAs), missing probes (if any), outliers etc. Do sanity check on the samples.
        - clustering analysis for data exploration
  * 3. Statistical analysis that can answer the research questions.
      - Statistical testing to identify differential DNA methylation regions
        * t-test (?__does this work?__), ANOVA, linear model
      - Multiple testing
      - Cluster analysis to identify subgroups
      - (check the course syllabus)

**Comment by kmnip** [comment]
Now that we know that we just need one paragraph, things is alot easier than we have imagined.

I think we can condense the first paragraph even further.
https://github.com/santina/CrystalMethylation/blob/master/initial_project_summary.md

**Comment by kmnip** [comment]
@Rashedul Please update your profile on our doc for the [initial project summary](https://github.com/santina/CrystalMethylation/blob/master/initial_project_summary.md) because we will need to post it on the class discussion page.

@BerylZhuang @santina @evayap @Rashedul So, should we trim down the description any further? especially the first paragraph? what do you think?

**Comment by kmnip** [comment]
trimmed first paragraph in 927b91e as we don't need too much details for background

**Comment by evayap** [comment]
@kmnip imo we need to mention how DNA methylation causes cancer. I made some changes, I'm thinking of removing the example for field defect. what do you guys think?

**Comment by kmnip** [comment]
Removed that line.
I think we can talk about this if we notice anything interesting when
comparing normal peripheral tissue from cancer patient against tissue from
normal patient.

**Comment by kmnip** [comment]
Should we refer to our [more detailed proposal](https://github.com/santina/CrystalMethylation/blob/master/Group_proposal.md) in our [initial project summary](https://github.com/santina/CrystalMethylation/blob/master/initial_project_summary.md)?

**Comment by evayap** [comment]
errr. I say we add that part about comparing tumours with paired normal tissues but delete the example. And nope, the detailed proposal is not completed yet...we're still missing very important information on methods.

**Comment by evayap** [comment]
the comparing tumour with paired normal tissues gives us the edge that we're considering all angles of abnormal methylation. also, for our dataset we mentioned normal tissues from CRC patients. so, I believe we should add that.

**Comment by kmnip** [comment]
Yes, I agree and I did keep that part:

>In this project, we aim to compare DNA methylation patterns (specifically hypermethylation of CpG islands) between normal tissues, colon adenomas, and colorectal tumours as well as comparison of tumours with paired normal tissues from CRC patients.

**Comment by kmnip** [comment]
Should we add a few one-liners about statistics approaches?

**Comment by evayap** [comment]
@kmnip i added that sentence i mentioned to you. that's very important to introduce the concept of field defect. and nope, i don't think statistical approach is required, at least it wasn't mentioned in the course outline.

**Comment by evayap** [comment]
just one suggestion, can someone let a friend read our proposal summary? I want to make sure that people can make the connection that when we mention comparing tumours with paired normal in CRC patients, we're indeed trying to identify markers mediating field defect.

**Comment by Rashedul** [comment]
Guys,

Finally, its in a paragraph. Look great.....:)

Ka Ming,

I like stats but I'm not an expert....updated.


RASHEDUL ISLAM
MSc student, Bioinformatics, UBC

**Comment by kmnip** [comment]
it was just a joke because the instructors would like us to have a mixed
background.

**Comment by evayap** [comment]
guyss.. my interest and expertise are so plain lol

**Comment by evayap** [comment]
can i say that i fight unicorns by night? and biochemist by day? ahha

**Comment by Rashedul** [comment]
Eva,

Only you make our group mixed. Otherwise, rest biof people very
similar/overlapping expertise.....lol

RASHEDUL ISLAM
MSc student, Bioinformatics, UBC

**Comment by santina** [comment]
It looks really good now. Eva does provide an element of diversity in our group.

**Comment by santina** [comment]
I have submitted it to the [course discussion issue](https://github.com/STAT540-UBC/Discussion/issues/22). 
Closing the issue now~  Note that this issue is no longer for the original proposal, but for the one-paragraph proposal.

**Comment by Rashedul** [comment]
yaaa, great.


RASHEDUL ISLAM
MSc student, Bioinformatics, UBC
