### ISSUE TITLE
Downsizing probes

### ISSUE THREAD

**Issue by santina** [santina/CrystalMethylation#2]
I removed the in-line comments from our proposal because I wanted to help finalize the proposal and save the discussion elsewhere. I think it was Eva who wrote this? How do you know it downsize to 30%? 

=======
*I think if we focus on CpG islands only, we should be able to downsize the probes enough. At least, that was what Alice's group did and What do you guys think?*
```
I have just verified. The GPL13534 data table has a column for 'Relation_to_UCSC_CpG_Island'.
- 150254 Island
-   24844 N_Shelf
-   62870 N_Shore
-   22300 S_Shelf
-   49197 S_Shore
- 176112 *blank*

~36% reduction if we remove blanks.
Relationship to Canonical CpG Island: Shores - 0-2 kb from CpG island; Shelves - 2-4 kb from CpG island.
~70% reduction if we focus on canonical CpGs only!!!
```

=======

**Comment by evayap** [comment]
ka ming wrote it, i just suggested we only look at CpG islands to downsize. shores and shelves aren't as interesting anyway.

**Comment by kmnip** [comment]
Yes. I just wanted to show you that we would have only 150,254 probes that map to canonical (UCSC hg18 annotations) CpG islands.

150254/485577 = 30.94%
which is equivalent to ~70 reduction as mentioned.

I will take of it.

**Comment by kmnip** [comment]
@santina FYI: This is how I got the numbers.

1. Download the full table (~200MB) from:
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48684

2. From a UNIX terminal, run the command:

```
grep -v '^#' GPL13534-11288.txt | cut -f 26 | sort | uniq -c
```
would return:
```
 176112 
 150254 Island
  24844 N_Shelf
  62870 N_Shore
      1 Relation_to_UCSC_CpG_Island
  22300 S_Shelf
  49197 S_Shore
```
`grep -v '^#' GPL13534-11288.txt` to skip the header lines, which starts with '#'
`cut -f 26` to extract column 26, which is 'Relation_to_UCSC_CpG_Island'
`sort` to sort values in lexicographical order
`uniq -c` to report only unique values and display the counts

176112 probes not in the vicinity of any CpGs; blank = no relation
150254 probes on CpGs (the interesting juicy probes).
'Relation_to_UCSC_CpG_Island' is just the column header of the table.
